title: Kenya Avocado Industry Support Programme
description: On this site are key documents produced by the Kenya Avocado Industry Support Programme (KAISP).
show_downloads: true
baseurl: "/kaisp"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


